# site settings
title: Alexia Crawford
subtitle: looking for an internship
email: alexia.crawford@gmail.com
description: My website to get to know me and some of the things I have worked on. It is still a work in progress, so please bear with me!
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "alexiacrawford.github.io"
# author:
city: San Francisco
state: CA
# country: United States of America
phone: (415) 713-6601

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  LinkedIn: www.linkedin.com/in/alexia-crawford-5a063b134

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
